In [1]:
import pandas as pd
import numpy as np
from math import exp,log,sqrt
from scipy.stats import binom

In [3]:
test=pd.DataFrame(np.random.rand(3,2),
columns=['foo','bar'],index=['a','b','c'])
test

foo       bar
a  0.498393  0.884014
b  0.151390  0.001143
c  0.231494  0.210486

In [4]:
test['my']=test.foo*2
test

foo       bar        my
a  0.498393  0.884014  0.996785
b  0.151390  0.001143  0.302779
c  0.231494  0.210486  0.462988

In [5]:
0.794**10

0.09958754450821711

In [8]:
sqrt(0.1)

0.31622776601683794

In [7]:
sum=0
for i in range(50,138):
    sum+=binom.pmf(i,137,0.4)
sum

np.float64(0.8220955881474251)

In [ ]:
import numpy as np
# reshape: 형상 변경
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print(reshaped)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# ravel과 flatten: 1차원으로 평탄화
flat_view = reshaped.ravel() # 뷰 반환
print(flat_view)    
flat_copy = reshaped.flatten()  # 사본 반환
print(flat_copy)
# newaxis를 사용한 차원 추가
arr = np.array([1, 2, 3])
row_vec = arr[np.newaxis, :]    # shape: (1, 3)
col_vec = arr[:, np.newaxis]    # shape: (3, 1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
