In [1]:
import numpy as np
v=np.array([1,2,3,4,5,6])
print(v)

[1 2 3 4 5 6]


In [2]:
from numpy import array #plus vector
v=array([3,2])
w=array([1,4])
print(v+w)

[4 6]


In [3]:
v=array([3,1]) #scalar multiplication
print(3*v)

[9 3]


In [4]:
from numpy import array
basis=array([[4,1],[0,2]])
v=array([1,1])
basis2=basis.transpose()
print(basis)
print(basis2)

[[4 1]
 [0 2]]
[[4 0]
 [1 2]]


In [5]:
from numpy import array
iHat=array([2,0]) #x of v is duplicate of iHat.
jHat=array([1,3]) #y of v is duplicate of jHat. and iHat+jHat is v.
v=array([2,1])
newV2=array([iHat,jHat]).dot(v)
print(newV2)

basis=array([iHat,jHat]).transpose()
newV=basis.dot(v)
print(newV)

[4 5]
[5 3]


In [6]:
newC=array([jHat,iHat]) #change iHat and jHat, and dot, different value.
print(newC.dot(v))

[5 4]


In [9]:
from numpy import array as arr
iHat1=arr([0,1])
jHat1=arr([-1,0])
trans1=arr([iHat1,jHat1]).transpose()

iHat2=arr([1,0])
jHat2=arr([1,1])
trans2=arr([iHat2,jHat2]).transpose()

combined=trans1@trans2
print(combined)

[[ 0 -1]
 [ 1  1]]


In [8]:
v=arr([1,2])
print(combined.dot(v))

[-2  3]


In [11]:
from sympy import *
A=Matrix([[4,2,4], #4x+2y+4z=1
        [5,3,7], #5x+3y+7z=2
        [9,3,6]]) #9x+3y+6z=3
inverse=A.inv()
identity=A*inverse
print(identity)
print(inverse)
print(inverse*Matrix([1,2,3])) #result is answer of x,y,z.
#wow

Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
Matrix([[1/2], [-5/2], [1]])


In [14]:
from numpy import array as arr
from numpy.linalg import inv
A=arr([[4,2,4], #4x+2y+4z=1
        [5,3,7], #5x+3y+7z=2
        [9,3,6]]) #9x+3y+6z=3
print(A)
print(inv(A))
print(inv(A)@arr([1,2,3])) #result is answer of x,y,z.
#wow

[[4 2 4]
 [5 3 7]
 [9 3 6]]
[[-5.00000000e-01  9.86864911e-17  3.33333333e-01]
 [ 5.50000000e+00 -2.00000000e+00 -1.33333333e+00]
 [-2.00000000e+00  1.00000000e+00  3.33333333e-01]]
[ 0.5 -2.5  1. ]


In [18]:
from numpy import array,diag
from numpy.linalg import eig,inv
A=array([[1,2],
        [4,5]])
eigenvals,eigenvecs=eig(A)
print('eigenvals : ',eigenvals)
print('eigenvecs : ',eigenvecs)

Q=eigenvecs
R=inv(Q)

L=diag(eigenvals)
B=Q@L@R
print('reconstructed : ',B)


eigenvals :  [-0.46410162  6.46410162]
eigenvecs :  [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]
reconstructed :  [[1. 2.]
 [4. 5.]]
